config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :pools do
    member do
      get :bets
      get :results
      get :elimination_bets
    end
    resources :registrations, only: [:index, :destroy] do
      get :register, on: :member
    end
  end

  resources :bets, except: [:new, :create, :show]

  resources :users do
    member do
      get :bets
      post :create_bets
      delete :destroy_bets
    end
  end

  resources :matches, except: :show do
    resources :scores, except: :show
  end

  resources :elimination_matches, except: :show
  resources :elimination_bets, except: :show


  resources :groups, except: :show

  resources :answers, only: :update

  get 'documents/my_bets/:pool_id', to: "documents#my_bets", as: 'documents_my_bets'
  get 'documents/all_bets/:pool_id', to: "documents#all_bets", as: 'documents_all_bets'

  post '/contact', to: 'home#contact', as: 'contacts'
  post '/registrations', to: 'home#registration', as: 'registrations'
  get '/dashboard', to: 'dashboard#index', as: 'dashboard'

  authenticated :user do
    root 'dashboard#index', as: 'authenticated_root'
  end

  root 'home#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  ### thirt party
  devise :database_authenticatable, :rememberable, :trackable, :validatable
  ### relations
  has_many :bets, dependent: :delete_all
  has_many :elimination_bets, dependent: :delete_all
  has_many :answers, dependent: :delete_all
  has_many :pools, -> { distinct }, through: :bets
  has_many :e_pools, -> { distinct }, through: :elimination_bets, source: :pool

  ### scopes
  scope :order_by_last_name, -> { order(:last_name) }
  ### validations
  validates_presence_of :name, :last_name, :email
  validates_uniqueness_of :email, :nickname
  ### Callbacks
  before_save :set_nickname

  ### instance methods
  def full_name
    "#{name} #{last_name}"
  end

  def create_bets_from(pool)
    Bet.create_all_bets_for(self, pool)
  end

  def create_elimination_bets_from(pool)
    EliminationBet.create_all_bets_for(self, pool)
  end

  def create_answer_for(pool)
    Answer.create_answer_for(self, pool)
  end

  def admin?
    role == "admin"
  end

  def regular?
    role == "regular"
  end

  def bets_in_pool(pool)
    bets.where(pool_id: pool.id).includes(match: :group)#.order('matches.group_id')
  end

  def elimination_bets_in_pool(pool)
    elimination_bets.where(pool_id: pool.id).includes(:elimination_match)#.order('matches.group_id')
  end

  def bets_in_pool_with_date(pool, date)
    bets.joins(:match).where('matches.date = ?', date).where(pool: pool).order('bets.pos')
  end

  def elimination_bets_in_pool_with_date(pool, date)
    elimination_bets.joins(:elimination_match).where('elimination_matches.date = ?', date).
    where(pool: pool).order('elimination_matches.match_number')
  end

  def answer_of_pool(pool)
    answers.where(pool_id: pool.id).first
  end

  def total_points_in_pool(pool)
    bets.where(pool_id: pool.id).sum(:points)
  end

  def total_elimination_points_in_pool(pool)
    elimination_bets.where(pool_id: pool.id).sum(:points)
  end

  def active_pools
   (pools.active + e_pools.active).uniq
  end

  def all_pools
    (pools + e_pools).uniq
  end

  def find_pool(id)
    pool = pools.where(id: id)
    e_pool = e_pools.where(id: id)
    (pool + e_pool).first
  end

  def last_active_pool
    active_pools.order(:updated_at).last
  end

  def delete_bets_of_pool(pool)
    bets_in_pool(pool).delete_all
  end

  def delete_elimination_bets_of_pool(pool)
    elimination_bets_in_pool(pool).delete_all
  end

  def delete_anwser_of_pool(pool)
    answer_of_pool(pool).delete
  end

  private
    def set_nickname
      self.nickname = [name, last_name].join("_").underscore unless nickname.present? and name.present?
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, except: [:index, :new, :create]
  before_action :check_params_password, only: :update
  authorize_resource

  def index
    @users = User.all.order_by_last_name
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      UserMailer.new_user_email(@user, @user.password).deliver_now
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to users_url, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url
  end

  def bets
    @pools = Pool.all #Pool.active_for_user(@user)
    # redirect_to(users_path, notice: "No hay Quinielas activas") if @pools.empty?
  end

  def create_bets
    if params[:pool_id]
      pool = Pool.active.find(params[:pool_id])
      @user.create_bets_from(pool)
      @user.create_elimination_bets_from(pool)
      @user.create_answer_for(pool)
      redirect_to users_url, notice: "Apuestas creadas con exito!"
    else
      redirect_to bets_user_path(@user), notice: 'Seleccione una Quiniela activa'
    end
  end

  def destroy_bets
    if params[:pool_id]
      pool = @user.find_pool(params[:pool_id])
      @user.delete_bets_of_pool(pool)
      @user.delete_elimination_bets_of_pool(pool)
      @user.delete_anwser_of_pool(pool)
      redirect_to users_url, notice: "Apuestas Eliminadas con exito!"
    else
      redirect_to bets_user_path(@user), notice: 'Seleccione una Quiniela del Usuario'
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params[:user].permit!
    end

    def check_params_password
      if params[:user][:password].blank?
        params[:user].delete(:password)
        if params[:user][:password_confirmation].blank?
          params[:user].delete(:password_confirmation)
        end
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper

  def display_user_pools(pools)
    li = ""
      li += content_tag(:span, "Quinielas:", class: "title")
      pools.each do |pool|
        li += content_tag :li  do
          content_tag(:span, pool.name, class: "label label-default")
        end
      end
    content_tag :ul, raw(li), class: "user-pool-list"
  end
end

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>
  <%= f.input :name, disabled: current_user.regular? %>
  <%= f.input :last_name, disabled: current_user.regular? %>
  <%= f.input :nickname, disabled: current_user.regular?  %>
  <%= f.input :phone, disabled: current_user.regular? %>
  <%= f.input :email, disabled: current_user.regular? %>
  <% if current_user.admin? %>
    <%= f.input :bonus_points %>
  <% end %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>
  <% if current_user.admin? %>
    <%= f.input :role, collection: ["admin", "regular"], input_html: { class: "chosen-select" } %>
  <% end %>
  <%= f.button :submit, class: "btn btn-success" %>
  <%= link_to "Volver", users_path, class: "btn btn-default" %>
<% end %>

app/views/users/bets.html.erb
<%= index_panel("Agregar usuario a Quiniela", false, "#", users_path ) do %>
  <div class="row">
    <div class="col-md-5">
    <table class="table table-condensed table-striped">
      <thead style="background-color: #3C3C3B; color: #FFF">
        <tr>
          <th colspan="2">Quinielas Disponibles</th>
        </tr>
      </thead>
    </table>
      <%= form_tag create_bets_user_path(@user), class: "form-inline" do %>
        <%= select_tag :pool_id, options_from_collection_for_select(@pools, :id, :name),
          class: "chosen-select form-control", style: "width: 350px",
          data: { placeholder: "Quinielas" } %>
        <%= submit_tag "Agregar", class: "btn btn-default" %>
      <% end %>
    </div>
    <div class="col-md-7">
    <table class="table table-condensed table-striped">
      <thead style="background-color: #3C3C3B; color: #FFF">
        <tr>
          <th colspan="2">Quinielas de Usuario</th>
        </tr>
      </thead>
      <tbody>
        <% @user.pools.each do |pool| %>
        <tr>
          <td><%= pool.name %></td>
          <td class="center">
            <%= destroy_table_button destroy_bets_user_path(@user, pool_id: pool.id) %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<%= form_panel("Editar Usuario") do %>
  <%= render 'form' %>
<% end %>

app/views/users/index.html.erb
<%= index_panel("Usuarios", can?(:create, User), new_user_path, dashboard_path) do %>
  <% if @users.any? %>
    <table class="table">
      <thead>
        <tr>
          <th>Apellidos</th>
          <th>Nombres</th>
          <th>Nick Name</th>
          <th>Telefono</th>
          <th>Bonificacion</th>
          <th>Email</th>
          <th class="center">Acciones</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.last_name %></td>
            <td><%= user.name %></td>
            <td><%= user.nickname %></td>
            <td><%= user.phone %></td>
            <td><%= user.bonus_points %></td>
            <td><%= user.email %></td>
            <td class = "center">
              <% if can? :read, user %>
                <%= show_table_button user %>
              <% end %>
              <% if can? :edit, user %>
                <%= edit_table_button edit_user_path(user) %>
              <% end %>
              <% if can? :destroy, user %>
                <%= destroy_table_button user %>
              <% end %>
              <% if can?(:create_bets, user) && user.regular? %>
                <%= link_to_create_bets bets_user_path(user) %>
              <% end %>
            </td>
          <% if user.regular? %>
            <tr>
              <td colspan="8"><%= display_user_pools(user.active_pools) %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <%=  mssg_for_empty_table %>
  <% end %>
<% end %>

app/views/users/new.html.erb
<%= form_panel("Nuevo Usuario") do %>
  <%= render 'form' %>
<% end %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>