config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :pools do
    member do
      get :bets
      get :results
      get :elimination_bets
    end
    resources :registrations, only: [:index, :destroy] do
      get :register, on: :member
    end
  end

  resources :bets, except: [:new, :create, :show]

  resources :users do
    member do
      get :bets
      post :create_bets
      delete :destroy_bets
    end
  end

  resources :matches, except: :show do
    resources :scores, except: :show
  end

  resources :elimination_matches, except: :show
  resources :elimination_bets, except: :show


  resources :groups, except: :show

  resources :answers, only: :update

  get 'documents/my_bets/:pool_id', to: "documents#my_bets", as: 'documents_my_bets'
  get 'documents/all_bets/:pool_id', to: "documents#all_bets", as: 'documents_all_bets'

  post '/contact', to: 'home#contact', as: 'contacts'
  post '/registrations', to: 'home#registration', as: 'registrations'
  get '/dashboard', to: 'dashboard#index', as: 'dashboard'

  authenticated :user do
    root 'dashboard#index', as: 'authenticated_root'
  end

  root 'home#index'
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag("logo.png"), dashboard_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Inicio", dashboard_path %></li>
        <% if can? :read, Group %>
          <li><%= link_to "Grupos", groups_path %></li>
        <% end %>
        <% if can? :read, Match %>
          <li><%= link_to "Partidos", matches_path %></li>
        <% end %>
        <% if can? :read, Bet %>
          <li><%= link_to "Apuestas", bets_path %></li>
        <% end %>
        <% if current_user.admin? %>
          <li><%= link_to "Quinielas", pools_path %></li>
          <li><%= link_to "Usuarios", users_path %></li>
        <% end %>

        <% if current_user.active_pools.any? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Mis Quinielas<b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
            <% current_user.active_pools.each do |pool| %>
            <li><%= link_to pool.name, pool_path(pool) %></li>
            <% end %>
            </ul>
          </li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <%= current_user.name %><b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Perfil", edit_user_path(current_user) %></li>
            <li class="divider"></li>
            <li><%= link_to "Salir", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_navbar_home.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag("logo.png"), root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Inicio", "#home", class: "home-menu-link" %></li>
        <li><%= link_to "Reglamento", "#rules", class: "home-menu-link" %></li>
        <li><%= link_to "Contacto", "#contact", class: "home-menu-link" %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li style="margin-right: 40px"><%= link_to "LOGIN", new_user_session_path,
          class: "btn btn-default" %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
</nav>